name: image-similarity
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - flask=1.1.2
  - waitress=2.0.0
  - pandas=1.4.1
  - requests=2.25.1
  - tensorflow=2.7.0
  - tensorflow-hub=0.12.0
  - matplotlib=3.5.3
  - scikit-learn=1.1.1
  - pip
  - pip:
      - tqdm==4.64.0
      - opencv-python==4.6.0.66